<section class="user-manager">
    <h2>Users</h2>
    <!-- The following logic is used to display error messages: -->
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission. Please correct them as indicated below.
        </p>
    <?php endif ?>

    <!-- The following block is used to generate the form HTML tag using the form object assigned to the view in the controller -->
    <?php echo $this->url(NULL,
        array('controller'=>'UserManager', 'action'=>'index'));
    ?>
    <!-- The following section is used to generate User Table -->
    <table class="table">
        <tr>
            <th>Name</th>
            <th>User ID / Email</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->name);?></td>
                <td><?php echo $this->escapeHtml($user->email);?></td>
                <td>
                    <a href="<?php echo $this->url(NULL,
                        array('controller'=>'UserManager', 'action'=>'edit', 'id' => $user->id));?>">Edit</a>
                    |
                    <a href="<?php echo $this->url(NULL,
                        array('controller'=>'UserManager', 'action'=>'confirmDelete', 'id' => $user->id));?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <a href="<?php echo $this->url(NULL,
        array('controller'=>'UserManager', 'action'=>'userAdd'));?>">Add User</a>
</section>