<section class="user-add">
    <h2>Add User</h2>
    <!-- The following logic is used to display error messages: -->
    <?php if ($this->error): ?>
    <p class="error">
        There were one or more issues with your submission. Please correct them as indicated below.
    </p>
    <?php endif ?>

    <!-- The following block is used to generate the form HTML tag using the form object assigned to the view in the controller -->
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL,
        array('controller'=>'UserManager', 'action'=>'userAddProcess')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <!-- The following section is used to generate individual form elements for the Name, Email, Password, Confirm Password, and Submit fields -->
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name')); ?></dd>

        <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email')); ?></dd>

        <dt><?php echo $this->formLabel($form->get('password')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password')); ?></dd>

        <dt><?php echo $this->formLabel($form->get('confirm_password')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password')); ?></dd>

        <dd><?php
            echo $this->formButton($form->get('submit'));
            echo $this->formElementErrors($form->get('submit')); ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>