<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="google-signin-client_id" content="515310922226-ra90c3np3ujrjb5cbqgqr53tci1hp9sj.apps.googleusercontent.com">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->url('users/upload-manager') ?>"><?php echo $this->translate('Communication Application') ?></a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('users/upload-manager') ?>"><?php echo $this->translate('Manage Documents') ?></a></li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('users/user-manager') ?>"><?php echo $this->translate('Manage Users') ?></a></li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('users/media-manager') ?>"><?php echo $this->translate('Manage Media') ?></a></li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('users/group-chat') ?>"><?php echo $this->translate('Group Chat') ?></a></li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('users/mail') ?>"><?php echo $this->translate('Send Mails') ?></a></li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('users/search') ?>"><?php echo $this->translate('Indexed Search') ?></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
