<section class="upload">
    <h2><?php echo $this->escapeHtml($upload->label);?></h2>
    <h4><?php echo $this->escapeHtml($upload->filename);?></h4>
    <img src="<?php echo $this->url('users/media-manager',
        array('action'=>'showImage',
            'id' => $upload->id,
            'subaction' => 'full'));?>" />
    <div align="center">
    <a href="<?php echo $this->url(NULL, array(
            'controller'=>'MediaManager',
            'action'=>'rotateImage',
            'id' => $upload->id,
            'subaction' => 'left'));?>">Rotate left</a>
    |
    <a href="<?php echo $this->url(NULL, array(
            'controller'=>'MediaManager',
            'action'=>'rotateImage',
            'id' => $upload->id,
            'subaction' => 'right'));?>">Rotate right</a>
    </div>
</section>
<a href="<?php echo $this->url('users/media-manager');?>">
    &raquo; Show Gallery</a>