<section class="mail-confirm">
    <h2>Message Sent Successful</h2>
    <div>
        <a href="<?php echo $this->url('users/upload-manager',
        array('controller'=>'UploadManager', 'action'=>'index', 'user_id' => $this->id));?>">My Uploads</a>
    </div>
    <div>
        <a href="<?php echo $this->url('users/group-chat',
            array('controller'=>'GroupChat', 'action'=>'index', 'user_id' => $this->id));?>">Group Chat</a>
    </div>
    <div>
        <a href="<?php echo $this->url('users/mail',
            array('controller'=>'GroupChat', 'action'=>'index', 'user_id' => $this->id));?>">Send Offline Messages</a>
    </div>
</section>