<section class="mail">
    <h2>Send Offline Message</h2>
    <!-- The following logic is used to display error messages: -->
    <?php if ($this->error): ?>
    <p class="error">
        There were one or more issues with your submission. Please correct them as indicated below.
    </p>
    <?php endif ?>

    <!-- The following block is used to generate the form HTML tag using the form object assigned to the view in the controller -->
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL,
        array('controller'=>'UploadManager', 'action'=>'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <!-- The following section is used to generate individual form elements for the Name, Email, Password, Confirm Password, and Submit fields -->
    <dl class="zend_form">
        <?php echo $this->form()->openTag($form); ?>
        <dt><?php echo $this->formLabel($form->get('fromUserName')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('fromUserName'));
            echo $this->formElementErrors($form->get('fromUserName')); ?></dd>

        <dt><?php echo $this->formLabel($form->get('comboToUsers')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('comboToUsers'));
            echo $this->formElementErrors($form->get('comboToUsers')); ?></dd>

        <dt><?php echo $this->formLabel($form->get('subject')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('subject'));
            echo $this->formElementErrors($form->get('subject')); ?></dd>

        <dt><?php echo $this->formLabel($form->get('message')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('message'));
            echo $this->formElementErrors($form->get('message')); ?></dd>

        <dd><?php
            echo $this->formButton($form->get('sendMail'));
            echo $this->formElementErrors($form->get('sendMail')); ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>